// Command Ops 2 Official Game Manual Extraction Database
window.manualDatabase = {
  "order_delay": {
    "title": "Order Delay (Emir Gecikmesi)",
    "pages": [121, 149, 150],
    "turkish_summary": "Command Ops 2 motorunda emir gecikmesi (Order Delay), bir emrin oyuncudan (Komutan) alınıp bağlı birliklere ulaştırılması ve planlanıp harekete geçilmesi için geçen süredir. Kılavuza göre:\n\n* **Zamanlama Planı (Page 121):** Bir gücün belirli bir saatte harekete geçmesini istiyorsanız, emri o saatten gecikme süresi kadar önce vermelisiniz. Eğer görevi belirli bir saatte bitirmelerini istiyorsanız, hem iletim gecikmesini hem de intikal/çatışma süresini hesaba katmalısınız!\n* **Gecikme Süresini Öğrenme (Page 121):** Bir karargahın (HQ) alt birimlerine emir iletmesinin ne kadar süreceğini görmek için; Haritadan HQ'yu seçin, *Force Data* penceresini açın ve yan menüdeki *Cmdr* sekmesine bakın. Buradaki **Force Delay** alanı, o HQ'ya bağlı birimlerin emri alıp harekete geçmesi için gereken tahmini süreyi gösterir.\n* **Hareket Hızları (Page 121):** Normal yol koşullarında ortalama hızlar:\n  * *Mekanize/Motorize Birlikler:* ~12 km/s\n  * *Piyade (Yaya) Birlikleri:* ~3 km/s\n  * Yorgun birlikler çok daha yavaş hareket eder. Düşmanla temas etmek (çatışma) ilerlemeyi devasa ölçüde yavaşlatır!\n* **Kritik Tavsiye (Page 121):** Asla taarruzun tam ortasında birliklere yeni hareket emirleri vermeyin (Replan cezası alır). En doğru zaman, taarruzun başarıyla sonuçlandığı ve yeniden yapılanma (reorg) veya sızma evresine girildiği andır.\n* **Hiyerarşik Yakınlık (Page 149):** Emir gönderenin birim boyutu arttıkça gecikme artar. Birliklerinizin emir gecikmesini düşürmek için onları organik karargahlarının (HQ) yakınında tutun.\n* **Mesafe ve Telsiz Gücü (Page 149):** Mesafe arttıkça gecikme katlanır. Motorize karargahlar daha güçlü telsizlere sahiptir ve daha uzak menzile yayın yapabilirler. Yaya veya süvari birlikleri ise ulaklar (runners) kullanmak zorunda kaldığı için karargahlarına çok daha yakın durmalıdır.",
    "raw_snippet": "To find out how long it will take your units to receive and process your orders: Select the HQ commanding the force you want to issue orders to. Open its Force Data dialog. Select the Cmdr Tab on the Sidebar. The Force Delay field tells you roughly how long it will take, in minutes, for all the units commanded by that HQ to receive an order and start moving.\n\nMotorised Units – average normal speed is 12 km/h on good roads.\nNon-Motorised ( Foot ) Units – average normal speed is 3 km/h on good roads. Tired units move slower. Contact with the enemy will make moves a lot slower!\n\nBecause the base delay increases as the force size of the effective sender goes up: Keep your units near their organic superiors, even if you are issuing orders directly to them. Another factor in Orders Delay is distance. The further away a unit is from its HQ, the longer it will take to receive orders. Distance has more of an impact if the HQ issuing orders is not motorised (either tracked or wheeled), because motorised units generally have more powerful radios."
  },
  "supply": {
    "title": "Line of Supply (İkmal & Lojistik)",
    "pages": [49, 115, 169],
    "turkish_summary": "Lojistik hatları, birliklerinizin mühimmat, yakıt ve temel gıda (Basics) ihtiyaçlarını karşılayan şebekedir. Resmi kılavuz verileri:\n\n* **İkmal Durumunu İzleme (Page 49):** Arayüzün altındaki *Cmd/Sup Lines* butonuna basıp ekranı 'Sup' moduna getirerek ikmal hatlarını görebilirsiniz. Çizgiler, seçili birimin bağlı olduğu üs (Base) veya İkmal Giriş Noktası (SEP) arasındaki yolu gösterir.\n* **Veri Güncelliği Gecikmesi (Page 49):** Haritada gördüğünüz lojistik çizgileri gerçek zamanlı olmayabilir! İşlemci yükünü azaltmak amacıyla ikmal hatları saatte bir hesaplanır. Çizgi yeşil görünse bile düşmanın o yolu çoktan kesmiş olabileceğini hesaba katmalısınız.\n* **48 Saatlik Dayanma Sınırı (Page 115):** İkmal hattı tamamen kesilen bir birlik, kendi mevcut depolarını tüketmeye başlar. Kılavuza göre, üs bağlantısı kopan bir askeri güç ortalama **48 saat (2 gün)** dayanabilir. Bu süreden sonra felaket sonuçlar başlar.\n* **İkmal Kesilmesinin Sonuçları (Page 115):** \n  * *Mühimmatsız kalırlarsa:* Kendilerini savunamazlar.\n  * *Yakıtsız kalırlarsa:* Motorize birimler tamamen hareketsiz kalır.\n  * *Temel İhtiyaçlar (Basics) biterse:* Kondisyonları hızla tükenir, yorgunluktan kurtulamazlar, moralleri sıfırlanır ve düşmana teslim olma (surrender) olasılıkları katlanır.\n* **Hattı Yeniden Kurma Yöntemleri (Page 115):** İkmal yolunu açmak için: \n  1) Dost bölgeye geri çekilin,\n  2) Hattı temizlemek için bir kurtarma gücü (relief force) gönderin,\n  3) Düşmanın yolu nereden kestiğini anlamak için küçük bir keşif grubunu üsse doğru geri gönderin.",
    "raw_snippet": "Supply lines indicate the last determined status of the supply line between the selected unit back up to its supply source ( Base or Supply Entry Point ) and, in the case of Bases, down to its drawing units.\n\nGet Your Units Back in Supply: Units that have their supply lines cut will not receive any resupply. In the interim they will continue to draw down their existing stocks. Normally you could expect a force cut off from its Base to last around 48 hours. Once their existing stocks are used up, they will be in peril.\n\nWithout ammo they will not be able to defend themselves. Without fuel motorised units will not be able to move and without Basics they will fatigue very quickly and recover from fatigue very slowly. Without Basics their morale will also start to drop. They will become very ineffective and will become increasingly more likely to surrender to the enemy."
  },
  "fatigue": {
    "title": "Fatigue and Rest (Yorgunluk ve Dinlenme)",
    "pages": [40, 116, 169],
    "turkish_summary": "Yorgunluk, birliklerin operasyonel verimliliğini doğrudan düşürür ve kış şartlarında ölümcül olabilir. Kılavuza göre:\n\n* **Dinlenme Hızı (Page 116):** Birlikler hareketsiz kaldığında, savunma yaparken veya beklerken yorgunlukları azalır. En hızlı dinlenme **Rest** emriyle gerçekleşir. Dondurucu soğuklarda birliklerinizi açık alan yerine kentsel/meskun (Urban) arazilerde dinlendirmek dinlenme hızını ciddi oranda artırır.\n* **Çatışma Altında Dinlenme Cezası (Page 116):** Dinlenme modundaki askerlerin muharebe kapasitesi düşer. Bu nedenle sadece sıcak çatışma hattının gerisinde, güvende olan birimlerinize Rest emri verin.\n* **İnisiyatif Uyku Hali (Page 116):** Eğer birlikler aşırı yorulursa (exhausted), verdiğiniz emirleri tamamen göz ardı ederek kendi inisiyatifleriyle oldukları yerde dinlenmeye (Rest) başlayabilirler. Yüksek eğitimli ve disiplinli birliklerin bu itaatsizliği yapma olasılığı daha düşüktür.\n* **Uykudan Uyandırma (Page 116):** Dinlenen birlikleri uyandırmak için onlara Rest dışında herhangi bir emir (Move, Defend vb.) verin. Ancak birlik hâlâ aşırı bitkin durumdaysa emri reddedip uyumaya devam edebilir. 'Bazen hiçbir zorlama yorgun bir askeri uyandıramaz.'\n* **Hava Durumu Etkisi (Page 40):** Aşırı düşük sıcaklıklar (Ardenler kışı) yorgunluğun atılmasını zorlaştırır. Birlikleri binalarda (Urban) dinlendirmek bu etkiyi nötrler.",
    "raw_snippet": "Whenever units are stationary and either resting, defending or waiting, their fatigue will reduce. Resting troops recover fastest. In cold weather your troops will recover faster in urban terrain. Resting units are not so good in a fire fight, so only order units to Rest if they are unlikely to be involved in serious combat.\n\nIf units become too tired, they may ignore any order you have given them and rest instead, where they are. Well-trained and fit units are less likely to do this.\n\nTo have your units wake up from resting: Order them to do anything other than Rest. However, if they went to Rest on their own initiative and they are still exhausted, they may again exercise their initiative and Rest instead. Sometimes, no amount of coercion will wake a tired soldier.\n\nExtreme temperatures will reduce your troops ability to recover fatigue, especially if they are not in urban terrain."
  },
  "cohesion": {
    "title": "Cohesion and Suppression (Uyum ve Baskı)",
    "pages": [116, 117],
    "turkish_summary": "Birim Uyum Seviyesi (Cohesion), askerlerin taktiksel bütünlüğünü ve organizasyon kalitesini temsil eder. Kılavuz kuralları:\n\n* **Uyum Kazanımı (Page 116):** Hareketsiz olan ve yeniden yapılanan (reorg), savunan veya bekleyen birimler zamanla cohesion kazanır. En hızlı kazanım **Reorg** (Yeniden Yapılanma) emriyle sağlanır.\n* **Reorg Verimliliği (Page 117):** Yeniden yapılanma (Reorg) emri verilen birimler, standart savunma pozisyonundaki (Defend) birimlere göre **2 kat daha hızlı** cohesion kazanır. Ancak Reorg modundaki birimler düşman topçu ateşine ve taarruzlarına karşı son derece savunmasızdır.\n* **İnisiyatif Reorg Hali (Page 117):** Eğer bir birim çok fazla dağılırsa (disorganized), emirlerinizi dinlemeyip olduğu yerde otomatik olarak Reorg sürecine girer. Takviye olarak paraşüt veya planörle (airborne) haritaya inen birlikler yere ayak bastıkları anda otomatik olarak Reorg modunda başlar.\n* **Arazide Yapılanma (Page 117):** Birimleri belirli bir koordinata gönderip orada Reorg yapmalarını sağlayabilirsiniz. Birim önce hedefe intikal edecek, ardından toparlanmaya başlayacaktır.",
    "raw_snippet": "Whenever units are stationary and either reorganising, defending, or waiting, they will recover cohesion i.e. become better organised. Reorganising troops recover fastest. However, they are vulnerable to enemy fire.\n\nNote that reorganising units recover cohesion twice as fast as defending units. If units become too disorganised, they may ignore any order you have given them and reorg instead, where they are. Well-trained and well-led units are less likely to do this. Invariably, reinforcements arriving by parachute or glider will automatically Reorg."
  },
  "artillery": {
    "title": "Artillery and Fire Support (Topçu & Atış Desteği)",
    "pages": [50, 89, 97],
    "turkish_summary": "Topçu desteği ve menzil halkaları, haritada planlama yaparken hayati önem taşır. Kılavuz kuralları:\n\n* **Menzil Halkaları (Page 50):** Doğrudan ateş gücü halkaları ikiye ayrılır:\n  * *APer (Anti-personnel / Piyade Savar):* Yeşil halkalar.\n  * *AArm (Anti-armour / Tank Savar):* Kırmızı halkalar.\n  * Her iki türün de 3 farklı tonu vardır: Maksimum Menzil (Açık ton), Etkin Menzil (Orta ton) ve Pusu Menzili (Koyu ton).\n* **Etkin ve Pusu Menzili Matematiksel Tanımı (Page 50):** \n  * *Effective Range (Etkin Menzil):* Maksimum ateş gücünün %33'ünün elde edilebildiği sınır.\n  * *Ambush Range (Pusu Menzili):* Maksimum ateş gücünün %67'sinin elde edilebildiği sınır.\n* **Topçu Menzil Sınırları (Page 50):** Dolaylı topçu atışlarında (Bombard) iki halka vardır: Siyah halka (Minimum menzil - topçunun kendi dibine vuramadığı alan) ve Mavi halka (Maksimum menzil).\n* **Topçuyu Taarruza Bağlama (Page 89):** Bir taarruz emrinde **Arty Direct Support Only** kutucuğunu işaretlerseniz, o topçular sadece o taarruza atış desteği sağlar ve başka birimlerin çağrılarına yanıt verip mühimmatlarını boşa harcamazlar.\n* **Karmaşık Taarruzlar (Complex Attacks) (Page 89):** Eğer alt birliklere (subHQs) sahip üst düzey bir HQ birimine taarruz emri verirseniz, sistem otomatik olarak 'Complex Attack' başlatır. Üst düzey HQ rezervde kalarak alt HQ'lara bağımsız taarruz görevleri atar.",
    "raw_snippet": "The two firepower types – anti-personnel (APer) (green rings), anti-armour (AArm) (red rings) each show 3 different color shades corresponding to 3 different ranges; maximum (light), effective (darker), and ambush (darkest). Effective range is the range at which 33% of the maxFP can be achieved. Ambush range is the range at which 67% of the maxFP can be achieved.\n\nFor indirect fire bombardment (Bombard) there is both a min (black ring) and a max (blue ring) range ring. The min ring delineates the area the unit cannot bombard into.\n\nArty Direct Support Only: Leave this checked to ensure that any assigned indirect fire support units will only support units assigned to this attack. If unchecked, they may support other friendly units and not be available when needed."
  }
};
